/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpprogrammer.prototypes.resizer;


import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


/**
 *
 * @author Tomasz Zajac
 */
public class ControlsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlsPanel
     */
    public ControlsPanel() {
        initComponents();
        init();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        DimentionSelector = new javax.swing.JComboBox<String>();
        DimentionValue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveType = new javax.swing.JComboBox<String>();
        DimentionSelector1 = new javax.swing.JComboBox<String>();
        DimentionValue1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutputPanel = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DimentionSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "width", "height" }));
        DimentionSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimentionSelectorActionPerformed(evt);
            }
        });

        DimentionValue.setToolTipText("");
        DimentionValue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DimentionValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimentionValueActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("new size in pixels:");

        jLabel3.setText("Drop imagas to the box below: ");

        saveType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "keep format", "save as .jpg", "save as .png" }));

        DimentionSelector1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "width", "height" }));
        DimentionSelector1.setSelectedIndex(1);
        DimentionSelector1.setEnabled(false);
        DimentionSelector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimentionSelector1ActionPerformed(evt);
            }
        });

        DimentionValue1.setToolTipText("");
        DimentionValue1.setEnabled(false);
        DimentionValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimentionValue1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("scale to one dimention");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        OutputPanel.setEditable(false);
        OutputPanel.setBackground(new java.awt.Color(204, 204, 204));
        OutputPanel.setColumns(20);
        OutputPanel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        OutputPanel.setForeground(new java.awt.Color(0, 0, 255));
        OutputPanel.setRows(5);
        jScrollPane2.setViewportView(OutputPanel);

        jButton2.setText("reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(DimentionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DimentionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DimentionSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DimentionValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DimentionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DimentionValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(saveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DimentionSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DimentionValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listeners.forEach( (value) -> { value.processFileList();});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DimentionValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimentionValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DimentionValue1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         setControlsEnabled();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
            
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void DimentionSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimentionSelectorActionPerformed
        DimentionSelector1.setSelectedIndex(DimentionSelector.getSelectedIndex()==0?1:0);
    }//GEN-LAST:event_DimentionSelectorActionPerformed

    private void DimentionSelector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimentionSelector1ActionPerformed
          DimentionSelector.setSelectedIndex(DimentionSelector1.getSelectedIndex()==0?1:0);
    }//GEN-LAST:event_DimentionSelector1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         listeners.forEach( (value) -> { value.reset();});
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DimentionValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimentionValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DimentionValueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DimentionSelector;
    private javax.swing.JComboBox<String> DimentionSelector1;
    private javax.swing.JTextField DimentionValue;
    private javax.swing.JTextField DimentionValue1;
    private javax.swing.JTextArea OutputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> saveType;
    // End of variables declaration//GEN-END:variables
    
    
    private final List<ControlsListener> listeners = new ArrayList<>(); 
    private boolean assetsReady = false; 
    
    /**
     *
     * @param listerner
     */
    
    public void reset(){
        jTextArea1.setText("");
        DimentionValue.setText("");
        DimentionValue1.setText("");
        OutputPanel.setText("Log:");
        jCheckBox1.setSelected(false);
        setAssetsReady(false);
    }
    
    public void addActionListener(ControlsListener listerner)
    {
        listeners.add(listerner);
    }
    
    public javax.swing.JTextArea dropTarget()
    {
        return jTextArea1;
    }
    
    public void setAssetsReady(Boolean value )
    {
        this.assetsReady = value;
        setControlsEnabled();
    }
    
    public void setControlsEnabled()
    {
        setControlsEnabled(assetsReady);
    }
    
    public JTextArea GetOutputPanel()
    {
        return OutputPanel;
    }
    
    public final void setControlsEnabled(Boolean value )
    {
        //System.out.println("setControlsEnabled");
        if(jCheckBox1.isSelected())
        {
            DimentionSelector1.setEnabled(false);
            DimentionValue1.setEnabled(false);
            if(getSizeValue() > 0)
            {
                jButton1.setEnabled(value);
            }else
            {
                jButton1.setEnabled(false);
            }
        }
        else
        {
            DimentionSelector1.setEnabled(true);
            DimentionValue1.setEnabled(true);
            if(getSizeValue() > 0 && getSizeValue1() > 0)
            {
                jButton1.setEnabled(value);
            }
            else
            {
                jButton1.setEnabled(false);
            }
        }
         jButton2.setEnabled(value);
    }
    
    public int getSizeValue()
    {
      return ControlsPanel.parseInt(DimentionValue.getText());
    }
    
    public int getSizeValue1()
    {
      return ControlsPanel.parseInt(DimentionValue1.getText());
    }
    public int getDimention()
    {       
        return DimentionSelector.getSelectedIndex();
    }
    
    public boolean getKeepAspectRatio()
    {       
        return jCheckBox1.isSelected();
    }
    
    public int getDimention1()
    {       
        return DimentionSelector1.getSelectedIndex();
    }
    
    public int getSaveType()
    {       
        return saveType.getSelectedIndex();
    }
    
    private static int parseInt(String input)
    {
        try 
        {
           return Integer.parseInt(input);
        } catch (NumberFormatException er) {
             System.out.println("invalid input value: "+ er.getMessage());
        }
          return 0;
    }

    public OutputData getOutputData()
    {       
        return new OutputData((DimentionSelector.getSelectedIndex() == 0 ? getSizeValue() : 0 ),
                              (DimentionSelector1.getSelectedIndex() == 1 ?  getSizeValue1() : (jCheckBox1.isSelected()?getSizeValue():0)),
                               saveType.getSelectedIndex()
                             );
    }
    
    private void init() 
    {
    //    Dimentions;
      setControlsEnabled(false);
      DocumentFilter fl = new DocumentFilter() {
            Pattern regEx = Pattern.compile("\\d+");
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {  
                Matcher matcher = regEx.matcher(text);
                if (text!="" && !matcher.matches()) {
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
               // textVauesChanged();
            }
        };
      DocumentListener dl = new DocumentListener(){
          @Override
          public void insertUpdate(DocumentEvent e) {
            textVauesChanged();
          }

          @Override
          public void removeUpdate(DocumentEvent e) {
            textVauesChanged();
          }

          @Override
          public void changedUpdate(DocumentEvent e) {
            textVauesChanged();
          }
      };

      ((AbstractDocument) DimentionValue.getDocument()).setDocumentFilter(fl);
      ((AbstractDocument) DimentionValue.getDocument()).addDocumentListener(dl);
      ((AbstractDocument) DimentionValue1.getDocument()).setDocumentFilter(fl); 
      ((AbstractDocument) DimentionValue1.getDocument()).addDocumentListener(dl);
    }
    
    private void textVauesChanged()
    {
        if(assetsReady)
        {
           setControlsEnabled(true);
        }
    }
}
